import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    const numToSend = async event => {
      event.preventDefault()

      location.href = './s/' + event.target.num.value
  
      //event.target.num.value
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Sendzap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo a Sendzap
        </h1>
      </main>

      <form onSubmit={numToSend}>
      <label htmlFor="num">Número</label>
      <input id="num" num="num" type="text" autoComplete="num" required />
      <button type="submit">Enviar</button>
    </form>

      <footer className={styles.footer}>
          Powered by Nify Tech
      </footer>
    </div>
  )
}
